app = "oxboard-demucs"
primary_region = "sjc"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"
  PORT = "8000"
  DEMUCS_MODELS_PATH = "/data/models"
  DEMUCS_GPU_ENABLED = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"

[mounts]
  source = "demucs_models"
  destination = "/data/models"